### ISSUE TITLE
[BUG] 表单button禁用功能不可用

### ISSUE THREAD

**Issue by aevioni** [imvkmark/poppy-dev-mgr-app#20]
## 后端禁用按钮方法调用不起作用

```php
    public function disableReset(): self
    {
        ArrayHelper::delete($this->buttons, 'reset');
        return $this;
    }

    public function disableSubmit(): self
    {
        ArrayHelper::delete($this->buttons, 'submit');
        return $this;
    }
```

## 页面没有根据返回按钮信息展示
![image](https://user-images.githubusercontent.com/9879953/173176940-cd8173ae-88dd-453c-8fc4-9385debb83d6.png)

**Comment by imvkmark** [comment]
![image](https://user-images.githubusercontent.com/150127/174745757-2c0620f4-38ee-46ab-91ff-d41f0e9d08fa.png)

已经匹配相应的数据
